#设置代理 proxy = http://123.123.123.123:8080
proxy = ""
# RPC Server Port
port = ":8888"
[slack]
    #是否开启slack告警通道,可同时开始多个通道0为关闭,1为开启
    openSlack=1
    #默认lark机器人地址
    slackUrl= "https://hooks.slack.com/services/T01AKTP0S23/XXXXXXXX"

[mail]
    #是否开启邮件
    openEmail=1
    #邮件发件服务器地址
    emailHost="smtp.qq.com"
    #邮件发件服务器端口
    emailPort=465
    #邮件帐号
    emailUser=""
    #邮件密码
    emailPassword=""
    #邮件标题
    emailTitle="运维告警"
    #默认发送邮箱
    defaultEmails=""

[lark]
    #是否开启lark告警通道,可同时开始多个通道0为关闭,1为开启
    openLark=1
    #默认lark机器人地址
    larkUrl="https://open.larksuite.com/open-apis/bot/v2/hook/XXXXXXX"

[dingding]
    # 是否开启钉钉告警通道,可同时开始多个通道0为关闭,1为开启
    openDingding=1
    #默认钉钉机器人地址
    ddUrl="https://oapi.dingtalk.com/robot/send?access_token=XXXXXXXX"
    #是否开启 @所有人(0为关闭,1为开启)
    ddIsAtAll=1


[wechat]
    #是否开启微信告警通道,可同时开始多个通道0为关闭,1为开启
    openWechat=1
    #默认企业微信机器人地址
    wechatUrl="https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=9c0ff503-0629-45a1-88bb-230a7b615234"