#设置代理 proxy = http://123.123.123.123:8080
proxy = ""
# RPC Server Port
port = ":8888"
[slack]
    #是否开启slack告警通道,可同时开始多个通道0为关闭,1为开启
    open-slack=1
    #默认lark机器人地址
    slackurl= "https://hooks.slack.com/services/T01AKTP0S23/B01B0LATRKL/XXXXXXX"

[mail]
    #是否开启邮件
    open-email=1
    #邮件发件服务器地址
    Email_host="smtp.qq.com"
    #邮件发件服务器端口
    Email_port=465
    #邮件帐号
    Email_user=""
    #邮件密码
    Email_password=""
    #邮件标题
    Email_title="运维告警"
    #默认发送邮箱
    Default_emails=""

[lark]
    #是否开启lark告警通道,可同时开始多个通道0为关闭,1为开启
    open-lark=1
    #默认lark机器人地址
    larkurl="https://open.larksuite.com/open-apis/bot/v2/hook/XXXXXX"

[dingding]
    # 是否开启钉钉告警通道,可同时开始多个通道0为关闭,1为开启
    open-dingding=1
    #默认钉钉机器人地址
    ddurl="https://oapi.dingtalk.com/robot/send?access_token=XXXXX"
    #是否开启 @所有人(0为关闭,1为开启)
    dd_isatall=1


[wechat]
    #是否开启微信告警通道,可同时开始多个通道0为关闭,1为开启
    open-wechat=1
    #默认企业微信机器人地址
    wechaturl="https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=XXXXX"
